### PR TITLE
Renaming classes to avoid confusion (master branch)

### PR DESCRIPTION
**Pull request by timo-schmid**
Hi

Thank you very much for the exercises! I learned a few things!

What I noticed was, that the objects had the same names as Scalaz's classes, which caused some confusion for me while writing (especially during the "Reader" excersise). Thus I took the liberty to prefix them with "Ex1-8" - to make it more clear.

Cheers!

Timo

### CODE REVIEW

**Comment by YannMoisan** [comment]
Thank you ! You're right, the naming is confusing !
I'd prefer to just have Ex as prefix to easily add an exercise between two existing exercises.
wdyt ?

**Comment by timo-schmid** [comment]
Sure, I can change it in the evening!

**Comment by timo-schmid** [comment]
Updated!

**Comment by YannMoisan** [comment]
I pushed a few commits in the meantime.
Could you sync your PR with the last commit ?

**Comment by YannMoisan** [comment]
I pushed a few commits in the meantime.
Could you sync your PR with the last commit ?

**Comment by timo-schmid** [comment]
I'll recreate the PR's, nasty merge conflicts ;-)

**Pull request closed without merging**
